### ISSUE TITLE
datagrid中的row或cell能添加自定义属性吗

### ISSUE THREAD

**Issue by lshfong** [easysoft/zui#100]
比如我想在datagrid的行对象添加一个自定义属性来存储每一行的userid，本来我想在行渲染中添加，但没有找到这个方法事件

**Comment by catouse** [comment]
你可以通过 `cellFormator` 选项来自己格式化单元格元素。官方使用 `cellFormator` 相关代码为：

```js
if (options.cellFormator) {
    options.cellFormator($cell, cell, that);
} else {
    var $content = isCheckbox ? $cell.find('.content') : $cell;
    $content[cell.config.html ? 'html' : 'text'](cell.value);
    if (config.className) {
        $cell.addClass(config.className);
    }
}
```

`cellFormator` 为一个回调函数用于格式化单元格元素，回调函数参数包括：

* `$cell`：要格式化的单元格元素；
* `cell`：当前单元格对象；
* `datagrid`：数据表格对象实例。

因为是用法问题，这个问题先关闭了，如果有其他问题再打开。
