### ISSUE TITLE
zui中有控制margin、padding的全局类吗

### ISSUE THREAD

**Issue by lshfong** [easysoft/zui#102]
zui中有控制margin、padding的全局类吗？还是需要自己单独写

**Comment by catouse** [comment]
ZUI 中今提供了如下与 margin、padding 有关的辅助类：

* `with-padding`：在元素内部四周添加内边距；
* `no-padding`：移除元素内部所有内边距，即 padding 设为 0；
* `no-margin`：移除元素外边距，即 margin 设为 0。

不推荐依赖辅助类来定制界面，应该依据元素在组件中的角色自定义更有意义 class，然后面向 class 来定制外观。

**Comment by lshfong** [comment]
感谢指点
