### ISSUE TITLE
赤裸裸的抄袭bootstrap啊，以前还没发现，最近看了boot才知道。

### ISSUE THREAD

**Issue by jarvan4dev** [easysoft/zui#11]

**Comment by Catouse** [comment]
http://zui.sexy/docs/start.html#intro

**Comment by easysoft** [comment]
zui的介绍里面很清楚的讲明了zui和bootstrap以及其他很多优秀组件的关系。
以后了解清楚再发表意见吧。还真是无知者无畏。
