### ISSUE TITLE
采用远程加载数据时，数据表格2的render()方法不能重新读取数据

### ISSUE THREAD

**Issue by eternaloil** [easysoft/zui#110]
需要在调用之前设置一下DataSource才能刷新数据。
`var data = {
					rowId : rowId,
					assessType : assessType
			}
			
			$.ajax({
				url:'pm_assess',
				data:JSON.stringify(data),
				type:'POST',
				contentType: "application/json",
				dataType: "json",
				error: function(data){
					$.zui.messager.show(data.responseText,{placement:'top-right'});
				},
				success: function(resData){
					var dataGrid = $('#todoTable').data('zui.datagrid');
					dataGrid.setDataSource(getDataSource());
					dataGrid.render();
				}
			})`

**Comment by catouse** [comment]
远程数据源不需要自己调用ajax请求，只需要设置数据源的 url 即可。如果 url 地址不变时由于缓存机制不会刷新，需要手动清除缓存，然后调用 render 方法：
```js

**Comment by liaodongxiaoxiao** [comment]
@catouse 按照您的方法，当数据列表只有一天数据时，把这条数据删除。清除缓存-》重新渲染，这条数据还是会在那。
