### ISSUE TITLE
zui.uploader.js 修改文件名时，若文件名长度和文件扩展名长度相同时,则文件扩展名丢失

### ISSUE THREAD

**Issue by o0iYi0o** [easysoft/zui#115]
第318行，
if(ext.length && !options.renameExtension && 
**filename.lastIndexOf('.' + ext) !== (filename.length - ext.length - 1)**) {
                                 filename += '.' + ext;
 }
这里的这个判断逻辑filename.lastIndexOf('.' + ext) !== (filename.length - ext.length - 1)有点问题，若是修改后的文件名长度和当前文件的扩展名长度相同（修改的名称中没有输入扩展名），则会出现修改后文件的扩展名丢失

**Comment by catouse** [comment]
see #116.
