### ISSUE TITLE
为什么文件上传超过1M就传为blob文件？

### ISSUE THREAD

**Issue by NicesMan** [easysoft/zui#117]
采用的是zui框架(http://zui.sexy/#view/uploader) 的文件上传
但是一旦文件上传超过1M，上传到服务器上就变为blob文件，且大小不符
后台是用的python的tornado框架

**Comment by catouse** [comment]
大文件会分片进行上传，你需要通过其他字段将文件名提交到服务器。

**Comment by NicesMan** [comment]
ok 问题已解决，十分感谢！
