### ISSUE TITLE
文件上传组件 文件状态标识官网网页与源码不符

### ISSUE THREAD

**Issue by luodongcn** [easysoft/zui#119]
文件上传组件 通过$.zui.Uploader.STATUS拿到的文件状态，官网标识如下：
 
状态 | 值 | 描述
-- | -- | --
STOPPED | 1 | 文件队列还没有开始上传，或者上传已暂停或已上传完成。
STARTED | 2 | 文件队列正在上传中。
QUEUED | 1 | 文件已被添加到上传队列中等待上传。
UPLOADING | 2 | 文件正在上传中。
FAILED | 3 | 文件上传失败。
DONE | 4 | 文件已上传到服务器。

通过断点进入源码发现文件标识不一样：
FAILED | 4 | 文件上传失败。
DONE | 5 | 文件已上传到服务器。

![debugger](https://user-images.githubusercontent.com/28913673/39169688-5c2e7396-47cb-11e8-8552-b586b784ba53.png)
![api](https://user-images.githubusercontent.com/28913673/39169690-5d0829a6-47cb-11e8-8bc3-c594787b807b.png)

**Comment by catouse** [comment]
非常感谢，正确的值是：
