### ISSUE TITLE
在数据表格2上，使用图片浏览插件会有问题

### ISSUE THREAD

**Issue by cnbrave** [easysoft/zui#125]
在数据表格2上，使用图片浏览插件会有问题，一开始是可以，但是滚动滚动条之后就不行了。
也就是用如下的代码会有问题：
< img data-toggle="lightbox" src="small-image.jpg" data-image="large-image.jpg" data-caption="小图看大图" class="img-thumbnail" alt="" width="200" >

需换成下面这个：
$('a.lightbox-toggle').lightbox({
    image: 'http://your/image/url.jpg',
    caption: '图片说明'
});

使用的浏览器是QQ浏览器，chrome内核。

**Comment by catouse** [comment]
目前不支持这种用法，因为数据表格内的内容都是滚动即时生成的，之前绑定的事件会消失。你可以这样：

```js
var lightbox = $('< img data-toggle="lightbox">').lightbox().data('zui.lightbox');
$('#myDataGrid').on('click', '[data-toggle="lightbox"]', function() {
    var $img = $(this);
    lightbox.show($img.data('image'), $img.data('caption'));
});
```
