### ISSUE TITLE
Error: Cannot find module './zui.templates.json'

### ISSUE THREAD

**Issue by xiaoge2017** [easysoft/zui#137]
![image](https://user-images.githubusercontent.com/28918650/48963100-ad02b900-efc6-11e8-9cb0-bcc9807c5297.png)
![image](https://user-images.githubusercontent.com/28918650/48963102-b1c76d00-efc6-11e8-87e3-d7c968719fba.png)
重新编译less这里改一下提示或者文件名吧

**Comment by catouse** [comment]
已解决。
