### ISSUE TITLE
数据表格2的remoteConverter能否给个demo代码？

### ISSUE THREAD

**Issue by mengxin-FE** [easysoft/zui#139]
数据表格2的remoteConverter能否给个demo代码？

表格一直弹 无法处理远程服务器返回的数据。

**Comment by stalleHo** [comment]
remote:function (params,datagrid) {
                    return{
                        url:URL,
                        type:"GET",
                        dataType:"json"
                    };
                }，
                // 远程数据不符合格式要通过  remoteConverter自己手动修改
                remoteConverter:function (responseData,textStatus) {
                  //这是修改的动作 S---------------------------------------------
                    var data = [],
                        pager = {
                            page:responseData.info.page,
                            recTotal:responseData.info.results,
                            recPerPage:20
                        };
                    $.each(responseData.results,function (idx,val) {
                        var item = {
                            username:val.login.username,
                            uuid:val.login.uuid,
                            email:val.email,
                            phone:val.phone,
                            gender:val.gender,
                            id:val.id.name+"_"+val.id.value
                        };
                        data.push(item);

                    });
                    var remoteData = {
                        result:textStatus,
                        data:data,
                        message:'提示消息',
                        pager:pager
                    };
                 //这是修改的动作 E---------------------------------------------
                
                //把改好的对象return出去就好了
                    return remoteData;
                }
`
`

**Comment by catouse** [comment]
@stalleHo 的例子很清楚了，先关闭这个问题。
