### ISSUE TITLE
数据表格2 远程使用分页时，会访问两次

### ISSUE THREAD

**Issue by zelricx** [easysoft/zui#151]
数据表格2 远程使用分页时，当选择除第一页意外的页数，会访问一次该页，之后立马访问第一页

PS：已使用1.9.1版本

**Comment by love-xu** [comment]
这个你需要设置下
states: {
    pager:{
        page:1, // 当前页码，默认为0，你后台返回的应该是1
        recPerPage: 10//每页数量，默认为10.
    }
}
