### ISSUE TITLE
关于KindEditor在PJAX中使用的BUG

### ISSUE THREAD

**Issue by fonhen** [easysoft/zui#153]
KindEditor在PJAX中使用的BUG

BUG描述: 无法获取焦点(用户无法在编辑器中输入)

还原过程:

1.在A页面创建一个编辑器(KindEditor)
2.点击其它页面的链接跳转
3.通过浏览器返回上一页(包含编辑器的页面)
4.此时编辑器就处于无法编辑器的状态

**Comment by catouse** [comment]
无法重现你的问题。

**Comment by easysoft** [comment]
跟浏览器会不会有关系？

**Comment by fonhen** [comment]
的火狐,谷歌,欧朋三个浏览器中都是一样的问题

**Comment by easysoft** [comment]
是在你们自己的项目中用的吧？你可以需要在自己的页面中做一下处理。处理下返回的事件，重新初始化编辑器。
