### ISSUE TITLE
弹出框取消后仍然有选中状态，BOOTSTRAP默认没此问题

### ISSUE THREAD

**Issue by fengsuxing** [easysoft/zui#16]
![qq 20160218112317](https://cloud.githubusercontent.com/assets/13061184/13132931/0a47f640-d632-11e5-82b7-2d34989c3584.jpg)
弹出框取消后仍然有选中状态，BOOTSTRAP默认没此问题

**Comment by fengsuxing** [comment]
需任意点击某处才会消失。。

**Comment by Catouse** [comment]
你是指“启动对话框”按钮在对话框关闭之后还是获取焦点的状态？

**Comment by fengsuxing** [comment]
是的。

**Comment by Catouse** [comment]
正常行为应该是：
1. 点击按钮，按钮获得焦点；
2. 打开对话框，对话框获得焦点 （已确认的问题：ZUI的按钮在此时仍然获得焦点）；
3. 关闭对话框，按钮重新获得焦点。
谢谢反馈！

**Comment by fengsuxing** [comment]
我觉得正常行为应该是：
1. 点击按钮，按钮获得焦点；
2. 打开对话框，对话框没有焦点；
3. 关闭对话框，对话框没有焦点。
BOOTSTRAP也是这样的

**Comment by fengsuxing** [comment]
可以参考http://www.runoob.com/try/try.php?filename=bootstrap3-plugin-modal
如果觉得我说的是错的，能否教我下怎样修改框架能让关闭后没有焦点~谢谢~~

**Comment by fengsuxing** [comment]
目前我不使用框架的button data-toggle，data-target能够实现，，，通过调用modal方法来处理就是正常的,但有强迫症，，还是希望指点一二，，直接改下zui框架修复此问题

**Comment by Catouse** [comment]
关闭后按钮重新获得焦点是正确的，你尝试换用最新的bootstrap，跟ZUI的行为是一致的。ZUI目前的问题是对话框打开之后对话框没有获得焦点。
如果你确实需要关闭后不让按钮获得焦点，你可以使用jQuery手动设置。
```html
<!DOCTYPE html>
<html>
<head>
   <title>Bootstrap 实例 - 模态框（Modal）插件</title>
   <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
   <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
   <style>.btn:focus {border:2px solid red}</style>
</head>
<body>
...example in http://www.runoob.com/try/try.php?filename=bootstrap3-plugin-modal
```

**Comment by fengsuxing** [comment]
那就是想通过直接改框架实现有点麻烦，只能在页面里都弃用button data-toggle，data-target属性了额？。。。
