### ISSUE TITLE
js 分页器如何去掉 URL上的参数

### ISSUE THREAD

**Issue by JHeLiu** [easysoft/zui#166]
js 分页器如何去掉 URL上的参数，
不想让它在我的地址上加入参数。是否用这种操作

**Comment by JHeLiu** [comment]
我尝试 把 参数 
`
linkCreator: function(page, pager) {}
`
可解决

**Comment by catouse** [comment]
对了，`linkCreator` 选项除了可以使用函数自定义之外，还可以使用模版字符串例如：`mysite.com/url?page={page}`。
