### ISSUE TITLE
有没有办法让ie9访问时不弹出提示版本太低的红色弹窗？

### ISSUE THREAD

**Issue by Billraozihan** [easysoft/zui#172]
如题，我的程序的运行环境比较特殊，实际显示效果是ie9，但html/js接收到的版本号是ie6。红色的提示框有些碍事。

**Comment by easysoft** [comment]
你说的是禅道吧。头文件里面有一个检测，删掉就行了

**Comment by Billraozihan** [comment]
> 你说的是禅道吧。头文件里面有一个检测，删掉就行了

注释了，没了，对话框报错， 取消注释，居然不提示了。也谢谢你的帮助
