### ISSUE TITLE
ie9是不能正常使用开关吗？

### ISSUE THREAD

**Issue by Billraozihan** [easysoft/zui#173]
如题，ie11可用，edgehtml可用，ie9不能正常开关。有解决办法吗？

**Comment by Billraozihan** [comment]
又测试了一下，ie9只能点击边框才有效果，又解决办法吗？

**Comment by Billraozihan** [comment]
又一个新发现：ie9下点击开关同一行右边的空白可以操作开关，唯独点击开关本体不行。。

**Comment by easysoft** [comment]
ie9不再提供支持。

**Comment by Billraozihan** [comment]
把checkbox本体的z-index调到比开关高就能解决部分问题
