### ISSUE TITLE
不显示字体图标

### ISSUE THREAD

**Issue by Billraozihan** [easysoft/zui#174]
rt，不止ie9，所有浏览器都不显示。zui.css内的路径已经修改正确，也试过引入fontawesome，都不行。不能显示的图标包括 轮播 的白色箭头， 图片浏览 (Lightbox)  的“x“和箭头。

**Comment by catouse** [comment]
检测一下浏览器网络日志是否正常下载了字体图标文件。
如果排除了路径问题，可能是你的服务器没有允许访问字体文件类型，参考下 [字体图标显示不出来的解决办法](https://blog.csdn.net/jiedao_liyk/article/details/59077206)。

**Comment by Billraozihan** [comment]
> 检测一下浏览器网络日志是否正常下载了字体图标文件。
> 如果排除了路径问题，可能是你的服务器没有允许访问字体文件类型，参考下 字体图标显示不出来的解决办法。

我的环境是类似nodejs的本地程序，js和css也全部在本地，整个程序是离线运行的。

**Comment by catouse** [comment]
检测一下浏览器网络日志是否正常下载了字体图标文件。

**Comment by Billraozihan** [comment]
> 检测一下浏览器网络日志是否正常下载了字体图标文件。

。。。。。本地脱机运行哪来的浏览器？

**Comment by Billraozihan** [comment]
> 网络日志

您可能理解错了，我的环境名叫mshta，兼容ie11，不是file协议运行html文件。

**Comment by catouse** [comment]
@Billraozihan 浏览器开发者工具 -> Networks
