### ISSUE TITLE
zui.calendar.js有致命错误（1.9.1版本）

### ISSUE THREAD

**Issue by JIMhackKING** [easysoft/zui#175]
第387行：有一个未定义的变量  fasle，
请修改为 false

**Comment by catouse** [comment]
能贴一下代码吗？

**Comment by JIMhackKING** [comment]
```javascript
// 从日历去除
$("#calendar").data('zui.calendar').removeEvents('job_calendar_' + id);
```
这段代码，是删除日历里面某个事项的，我是跟着文档去写的
![image](https://user-images.githubusercontent.com/23214854/85246397-1980bb00-b47d-11ea-8c0c-cad57d03ffc8.png)

然后报错就是这个啦：`Uncaught ReferenceError: fasle is not defined`

其实也很明显啦，是拼写错误，false 写成了 fasle，
在官网下载的文件里面路径为：lib/calendar/zui.calendar.js  第387行
在git文件里面路径为：dist/lib/calendar/zui.calendar.js  第391行

**Comment by JIMhackKING** [comment]
我提交一个pull request吧，改也很快，审核一下就好了

**Comment by JIMhackKING** [comment]
#176

**Comment by easysoft** [comment]
谢谢反馈。：）
