### ISSUE TITLE
datatable插件显示的横向滚动条效果只有拖到最下面才可以看到么？

### ISSUE THREAD

**Issue by BaiYangReal** [easysoft/zui#18]
我尝试用datatable插件做个列表显示，但是由于行数较多。
当我想查看第一条数据的后面几列的时候，需要把页面拉到最下面，
然后再把横向滚动条拉到后方的位置才能看到。

不知道是不是有存在类似于表头固定（fixedHeader）那样
固定表格的横向滚动条在显示范围下方的方法呢？

**Comment by Catouse** [comment]
你可以拖拽表头来滚动。

BaiYangReal <notifications@github.com>于2016年3月17日周四 16:56写道：
