### ISSUE TITLE
日历组件启动参数startDate无效

### ISSUE THREAD

**Issue by jiuling1029** [easysoft/zui#19]
启动参数startDate无效，查看代码后发现一个重复赋值问题，手动去掉后解决。
![qq 20160330194532](https://cloud.githubusercontent.com/assets/5250352/14141159/fd1017a2-f6af-11e5-9056-90811e825225.png)

错误在 lib/zui.calendar.js 102行，此处
`this.date = 'today';`
将上方99行的
`this.date = this.options.startDate || 'today';`
给重新赋值了。

**Comment by Catouse** [comment]
谢谢反馈。
