### ISSUE TITLE
标签管理器1.8的版本可以右键，现在1.10的版本右键不能用了

### ISSUE THREAD

**Issue by cuiwenyuan** [easysoft/zui#192]
![image](https://user-images.githubusercontent.com/12511022/143446115-0fa3fa15-e4ac-4e61-8854-b84f55e0930c.png)
下面是1.8的版本
![image](https://user-images.githubusercontent.com/12511022/143446163-776a4d1b-f6cb-4e61-bab0-322d48826758.png)

**Comment by catouse** [comment]
已解决。谢谢反馈。
