### ISSUE TITLE
ZUI3官网示例的hover会有重定位卡一下调整位置的情况

### ISSUE THREAD

**Issue by shaoerkuai** [easysoft/zui#217]
### 描述 (Description)

![image](https://github.com/easysoft/zui/assets/117460332/0387f0c2-070c-4d25-88a8-7142252424d8)

hover后文字出现了大概2px的重定位

![image](https://github.com/easysoft/zui/assets/117460332/7b4f8b58-4d41-4a5f-ba0e-dfc3f28239d1)

这里的hover存在指示三角的重定位

### 期望 (Expectation)

不产生重定位

### 结果 (Result)

当前hover会出现文字重定位和小三角重定位的情况，不是所有按钮都是如此，似乎和按钮的文字宽度有关系。

### 软件版本 (Software version)

3

**Comment by catouse** [comment]
在 Windows 和 macOS 上无法重现你说的问题。
![2](https://github.com/easysoft/zui/assets/472425/42181df1-50d2-4587-8544-bd6ed4ed375d)
