### ISSUE TITLE
exec.ts在windows 跑不起来docs:dev

### ISSUE THREAD

**Issue by shaoerkuai** [easysoft/zui#218]
### 描述 (Description)

![image](https://github.com/easysoft/zui/assets/117460332/61e3d210-372f-44ba-af6e-c0bd8de4f6e5)

### 期望 (Expectation)

期望windows能跑起来

### 结果 (Result)

由于spawn的问题，需要增加下系统判断

### 软件版本 (Software version)

3

**Comment by catouse** [comment]
谢谢反馈，已处理。
