### ISSUE TITLE
ZUI 1.10版本datagrid开启了行选择功能后，选择某个行，某行操作栏的绑定事件丢失

### ISSUE THREAD

**Issue by shaoerkuai** [easysoft/zui#219]
### 描述 (Description)

![image](https://github.com/easysoft/zui/assets/117460332/8945007a-8f6b-4c9a-93ec-574491872410)
![image](https://github.com/easysoft/zui/assets/117460332/276e4719-5ee7-4c94-86b7-39c9d19bbcbe)

### 期望 (Expectation)

期望操作列能正常在关闭checkByClickRow时事件监听正常。

不清楚为什么勾选会撤掉元素的监听器？？

操作栏是通过设置html:true，返回button元素。
button元素增加data-xxx绑定数据，然后jquery在document.ready时批量绑定click事件。

### 结果 (Result)

操作栏监听器在勾选行时被 撤掉了

### 软件版本 (Software version)

1.10.0

**Comment by catouse** [comment]
用委托事件吧
