### ISSUE TITLE
Vue3 是否能够使用？如何引入呢

### ISSUE THREAD

**Issue by noovertime7** [easysoft/zui#224]
### 描述 (Description)

Vue3 是否能够使用？如何引入呢，通过pnpm安装后引入报错main.ts:49 SyntaxError: The requested module '/node_modules/.vite/deps/zui.js?t=1726919114693&v=0d540a86' does not provide an export named 'default' 

### 期望 (Expectation)

正常使用

### 结果 (Result)

正常使用

**Comment by chergn** [comment]
他们这不像是组件库，更像是样式库。跟bootstrap5似的，都是使用class

**Comment by catouse** [comment]
ZUI3 不直接提供 Vue 组件，不过你可以使用 ZUI3 原生组件在 Vue 中进行使用，下面为一个简单的例子：

```vue
<template>
  <div ref="root" style="height:100%"></div>
</template>

<script setup lang="ts">
import {ref, onMounted} from 'vue';
import {DTable} from 'zui';

const props = defineProps<{options: Object}>();

const root = ref(null);
const dtable = ref(null);
onMounted(() => {
  dtable.value = new DTable(root.value, props.options);
});
</script>
```
