### ISSUE TITLE
建议，数据表格插件增加表头钉住功能

### ISSUE THREAD

**Issue by 178620086** [easysoft/zui#23]
需求是这样的，今天看到项目中的数据表格插件能锁定横向的评分之类的。
在oa或者管理后台之类的项目中，表格往往有很多行，往下滚动之后就忘记了哪一行叫什么名字。
希望也能钉住表头。

不知道我表述的清不清楚。如果不清楚请回复

**Comment by limeng0403** [comment]
冻结列也是有必须的，就像excel表格里的冻结功能一样。

**Comment by Catouse** [comment]
表头固定的功能已经提供了，不管需要一些设置，这个会在文档中更加详细的说明。
冻结列的功能实际上也提供了。
