### ISSUE TITLE
用来Chosen之后，输入组变成这样。。

### ISSUE THREAD

**Issue by echobailin** [easysoft/zui#26]
![image](https://cloud.githubusercontent.com/assets/16745078/15625825/d8b0f596-24e7-11e6-9d7d-b8ba9efeddd4.png)
![image](https://cloud.githubusercontent.com/assets/16745078/15625821/d3bda782-24e7-11e6-9a36-671988cce0d5.png)
用来Chosen之后，输入组变成这样。。

**Comment by Catouse** [comment]
.input-group 并没有适配 Chosen，而且在一个输入组中包含多个输入框也是不推荐的。
如果你需要在 .input-group 中包含chosen或者其他自定义内容，需要手动为添加的内容设置样式：`display:table-cell`，例如：
```
.input-group > .chosen-container {display:table-cell}
```
