### ISSUE TITLE
官方数据表格最后一个例子存在BUG

### ISSUE THREAD

**Issue by oncereply** [easysoft/zui#27]
![qq 20160706235656](https://cloud.githubusercontent.com/assets/1457297/16624987/6a342ce8-43d5-11e6-867d-b39965932e9f.png)
缩小浏览器，滚动至最后，当滚动到图中那个位置时点击“更新评分”按钮，会发现标题头浮动而且位置不对：
![qq 20160707000146](https://cloud.githubusercontent.com/assets/1457297/16625164/0585402e-43d6-11e6-99e3-7b66c39c78d1.png)

**Comment by Catouse** [comment]
确实如此，谢谢反馈。

答复哈 <notifications@github.com>于2016年7月7日周四 上午12:02写道：
