### ISSUE TITLE
使用dropdowm 改变宽度时不灵活

### ISSUE THREAD

**Issue by lzcaqde** [easysoft/zui#31]
当div.dropdown 设置宽度的时候，内容下面的div.dropdown>.dropdown-menu 并不会随之改变。若以插件的角度来看待，他们应该同时改变。

**Comment by Catouse** [comment]
我的观点与你恰恰相反，如果 .dropdown-menu 的宽度与 .dropdown 宽度一致将会限制下拉菜单使用场景，在[按钮组](http://zui.sexy/#component/buttongroup)中过小的宽度会有糟糕的体验。下拉菜单是浮现在页面之上的，任何时候都应该有合适的尺寸来显示菜单内容。如果你要定制 .dropdown-menu 的宽度非常简单，你可以使用 CSS 按需设置 width 值。
