### ISSUE TITLE
1.5.0版本漂浮消息报错：TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by galeo** [easysoft/zui#32]
以 `new $.zui.Messager(message)` 方式创建 Messager 实例即可触发。

报错位置：
https://github.com/easysoft/zui/blob/a224dd03402355124b4a3aaf9caae1798883eae7/src/js/messager.js#L38

由 a224dd034 引入

**Comment by Catouse** [comment]
谢谢反馈，已修复。
在新版本发布之前你可以这样来创建一个使用默认参数的 `Messager` 实例：

```javascript
new $.zui.Messager(message, {});
```
