### ISSUE TITLE
autocomplete需要优化一下

### ISSUE THREAD

**Issue by chenchao2016** [easysoft/zui#38]
autocomplete属性默认是打开的，但是在出现自动提示的时候这些提示会**_跟着页面滚动_**，遮住其他页面元素，体验比较差，这个地方至少给一个属性什么的，让用户选择**原生提示方式**或者你们**优化过的提示方式**吧。

**Comment by Catouse** [comment]
ZUI 目前并没有autocomplete 插件，不知道你说的是哪个。

**Comment by chenchao2016** [comment]
目前zui form下的input框的自动提示效果和原生自动提示不一样。zui的自动提示会随着页面一起滚动，类似于fixed的效果，但是原生不是这样的。autocomplete只是属性，不知道zui是不是处理过。



chaochen2016@sina.com
 
发件人： Catouse
发送时间： 2016-11-01 09:04
收件人： easysoft/zui
抄送： chenchao2016; Author
主题： Re: [easysoft/zui] autocomplete需要优化一下 (#38)
ZUI 目前并没有autocomplete 插件，不知道你说的是哪个。

**Comment by Catouse** [comment]
ZUI 并没有自动提示插件，也没有修改原生 autocomplete 功能。能否提供测试页面？

**Comment by chenchao2016** [comment]
在zui官网上的表单部分，在表单中输入文字，让他自动提示后，滚动页面，就发现问题了。截图如下：



chaochen2016@sina.com
 
发件人： Catouse
发送时间： 2016-11-01 10:10
收件人： easysoft/zui
抄送： chenchao2016; Author
主题： Re: [easysoft/zui] autocomplete需要优化一下 (#38)
ZUI 并没有自动提示插件，也没有修改原生 autocomplete 功能。能否提供测试页面？

**Comment by Catouse** [comment]
邮件中的图片无法显示。

**Comment by chenchao2016** [comment]
这下应该没问题了把



chaochen2016@sina.com
 
发件人： Catouse
发送时间： 2016-11-01 13:43
收件人： easysoft/zui
抄送： chenchao2016; Author
主题： Re: [easysoft/zui] autocomplete需要优化一下 (#38)
邮件中的图片无法显示。
