### ISSUE TITLE
zui.sexy网站路由失效

### ISSUE THREAD

**Issue by JashonWang** [easysoft/zui#42]
http://zui.sexy/ 网站路由失效，无法前进后退。不知去哪反馈，只能在这提交了。

**Comment by Catouse** [comment]
目前 http://zui.sexy 并没有完整的路由功能，前进后退功能将在后续版本中提供。谢谢反馈。

**Comment by Catouse** [comment]
目前 http://zui.sexy 并没有完整的路由功能，前进后退功能将在后续版本中提供。谢谢反馈。
