### ISSUE TITLE
图表控件在不刷新页面的情况下，重复渲染，当鼠标划过的时候，会显示旧的数据。

### ISSUE THREAD

**Issue by 5ftech** [easysoft/zui#46]
/*!
 * ZUI: Standard edition - v1.5.0 - 2016-09-06
 * http://zui.sexy
 * GitHub: https://github.com/easysoft/zui.git 
 * Copyright (c) 2016 cnezsoft.com; Licensed MIT
 */
——————————————————————
使用以上版本的zui程序,引用了zui.chart.min.js 

使用如下方法创建饼图
var myPieChart = $("#myPieChart").pieChart(data, options);
第一次渲染显示正常。

——————————————————————

再次使用调用
$("#myPieChart").pieChart(data, options);
第二次渲染，看似显示正常，但当鼠标划过图表的时候，图表会显示旧的数据，且新旧数据交替显示。

无奈之下，只能手动将旧的实例的数据清空
 var length = myPieChart.segments.length;
    for (var i = 0; i < length; i++) {
        instance.removeData();
        console.log(i)
    }
并再次渲染，才能得到没有旧数据的图表
$("#myPieChart").pieChart(data, options);

———————————————————————

期望结果：
每次重新渲染不需要手动清空旧的数据。
希望作者可以改进。

**Comment by Catouse** [comment]
当你需要更新图表时，无需重复创建图表，只需要修改数据后调用 `update()` 方法即可。

```js
// 更新第一个数据集的第三个数据值为50
myLineChart.datasets[0].points[2].value = 50;

// 调用update方法根据更新后的数据集重新绘制图表
myLineChart.update();
```

**Comment by Catouse** [comment]
你可以直接替换数据集：

```js
myLineChart.datasets = [...];
```
