### ISSUE TITLE
图表：柱状图不能显示颜色

### ISSUE THREAD

**Issue by 5ftech** [easysoft/zui#47]
/*!
 * ZUI: Standard edition - v1.5.0 - 2016-09-06
 * http://zui.sexy
 * GitHub: https://github.com/easysoft/zui.git 
 * Copyright (c) 2016 cnezsoft.com; Licensed MIT
 */

使用以上版本的zui ,调用柱状图（或者曲线图）

var data = {
    labels: ["一月", "二月", "三月", "四月", "五月", "六月", "七月"],
    datasets: [
        {
            label: "蓝队",
            color: 'primary',
            data: [65, 59, 80, 81, 56, 55, 40]
        }, {
            label: "绿队",
            color: 'green',
            data: [28, 48, 40, 19, 86, 27, 90]
        }
    ]
};

var options = {responsive: true}; // 图表配置项，可以留空来使用默认的配置
var myBarChart = $('#myBarChart').barChart(data, options);

但得到的图表只有灰黑色，没有办法显示彩色。

但调用饼图就能获得彩色的图像。

希望作者检查是否bug
希望作者能够改进。

**Comment by Catouse** [comment]
确保你使用的 ZUI 版本中包含[颜色插件](http://zui.sexy/#javascript/color)（ color.js），ZUI 1.5 标准版中已包含颜色插件。
如果使用的版本（例如 ZUI 1.5 简洁版）没有包含颜色插件，则不能在柱状图和曲线图中使用 color 选项来快速设置颜色，不过你仍然可以使用以下选项来设置数据配色：

```js
{
    fillColor: "rgba(220,220,220,0.2)",
    strokeColor: "rgba(220,220,220,1)",
    pointColor: "rgba(220,220,220,1)",
    pointStrokeColor: "#fff",
    pointHighlightFill: "#fff",
    pointHighlightStroke: "rgba(220,220,220,1)"
}
```

**Comment by catouse** [comment]
zui 1.7+以上的版本已不再需要包含颜色插件来使用color选项。
