### ISSUE TITLE
日期选择: 点击 X 清空日期，再次调开日期控件，此时不能进行月份的增减

### ISSUE THREAD

**Issue by 5ftech** [easysoft/zui#48]
/*!
 * ZUI: Standard edition - v1.5.0 - 2016-09-06
 * http://zui.sexy
 * GitHub: https://github.com/easysoft/zui.git 
 * Copyright (c) 2016 cnezsoft.com; Licensed MIT
 */

使用以上的zui版本文件，点击 X 清空日期，再次调开日期控件，此时不能进行月份的增减

**Comment by Catouse** [comment]
已记录将在新版本修复 http://pms.zentao.net/bug-view-982.html。

**Comment by Catouse** [comment]
在 1.6 中解决。
