### ISSUE TITLE
lib里集成的Kindeitor有问题

### ISSUE THREAD

**Issue by cos800** [easysoft/zui#49]
![tmp](https://cloud.githubusercontent.com/assets/635184/21672982/0bc5308c-d361-11e6-860b-539612f2dcee.png)

**Comment by Catouse** [comment]
暂时你可以手动将 ZUI 源码目录下的 assets/kindeditor/plugins 拷贝到你放置 kindeditor.js 的目录下解决。

**Comment by Catouse** [comment]
在 1.6 中解决。
