### ISSUE TITLE
图表控件不支持ie8

### ISSUE THREAD

**Issue by 5ftech** [easysoft/zui#50]
使用zui 1.5,并使用以上的兼容性代码，在ie8上使用图表控件,不能显示正常的饼图，线型图及柱状图。

**Comment by Catouse** [comment]
因为IE8及早期版本不支持Canvas，所以需要引入 ExplorerCanvas 来支持绘图功能。

```html
<!--[if lt IE 9]>
  <script src="dist/lib/ieonly/excanvas.js"></script>
<![endif]-->
```

另外如果你的 `<canvas>` 是在页面加载之后动态插入到页面的还需要手动调用如下方法：

```js
G_vmlCanvasManager.initElement(canvasElement);
```
