### ISSUE TITLE
表格缺少排序样式

### ISSUE THREAD

**Issue by blqw** [easysoft/zui#54]
表格缺少排序样式

**Comment by Catouse** [comment]
请问你所说的排序样式是指的什么呢？

**Comment by blqw** [comment]
点击列明出现排序的箭头
比如这种

**Comment by Catouse** [comment]
你可用在排序后在 `<th>` 标签内插入一些代表排序的图标。这些图标可用在官方文档通过 `i-sort` 关键字搜索到。
