### ISSUE TITLE
Uncaught TypeError: Cannot read property 'strCode' of undefined     at zui.uploader.js:49     at zui.uploader.js:897

### ISSUE THREAD

**Issue by alisaAsa** [easysoft/zui#59]
Uncaught TypeError: Cannot read property 'strCode' of undefined
    at zui.uploader.js:49
    at zui.uploader.js:897

**Comment by Catouse** [comment]
你需要在引入 `dist/lib/zui.uploader.js` 之前引入 ZUI 标准版 `dist/js/zui.js`。
