### ISSUE TITLE
仪表盘初始化时怎么设置初始化排序？

### ISSUE THREAD

**Issue by qzgyw** [easysoft/zui#60]
http://zui.sexy/#view/dashboard/1
初始化数据data中没有order选项，如果在用户拖动顺序后afterOrdered事件里保存了新的顺序，怎么在初始化的时候加载？

**Comment by Catouse** [comment]
`data` 选项数组内面板配置的顺序即为初始化时显示的顺序。如果是直接从页面 `.panel` 元素进行初始化，则安装页面显示的顺序进行初始化。
