### ISSUE TITLE
ie下无法使用dist\lib\calendar\demo.html

### ISSUE THREAD

**Issue by mzpuu** [easysoft/zui#62]
ie9 - ie11   calendar.addEvents(newEvents); 没有执行  events中为空

**Comment by Catouse** [comment]
需要更多信息才能理解你的问题。

**Comment by mzpuu** [comment]
在你的机器上ie9及以上可以使用dist\lib\calendar\demo.html？

**Comment by Catouse** [comment]
官方源码中 dist\lib\calendar\ 目录下并没有demo.html 文件。

**Comment by mzpuu** [comment]
一下截图是chrome 和 ie11的对比，增加事件在ie中没有效果

![qq 20170608102428](https://user-images.githubusercontent.com/7541466/26909717-2bfba0aa-4c35-11e7-8457-0f7f8cf7f07b.png)
chrome中
![qq 20170608102410](https://user-images.githubusercontent.com/7541466/26909718-2d472100-4c35-11e7-9a95-2c6699884110.png)

ie中
![qq 20170608102259](https://user-images.githubusercontent.com/7541466/26909731-3f8b78ac-4c35-11e7-8d2c-e852dd19e2d9.png)

**Comment by catouse** [comment]
经检查是 IE11 不支持直接将字符串转换为日期对象，最佳实践是指定日期时传入日期对象。官网示例已改。谢谢反馈。
```js
/* 增加多个事件 */
var calendar = $('#calendar').data('zui.calendar');
var newEvents =
[
  {title: '吃饭了', desc: '要吃更多', start: new Date(2018,1,4,12,10,0), end: new Date(2018,1,3,13,10,0)},
  {title: '学习了', desc: '要学更多', start: new Date(2018,1,3,13,10,0), end: new Date(2018,1,4,10,0,0)}
];
calendar.addEvents(newEvents);
```
