### ISSUE TITLE
拖放组件 selfTarget 属性一直返回true

### ISSUE THREAD

**Issue by blqw** [easysoft/zui#65]
http://zui.sexy/#javascript/droppable
无论什么情况 e.selfTarget 都等于 true

还有 
拖动元素的时候会在元素上加上 drag-in 的类样式, 结束拖放之后该样式不会被移除

**Comment by catouse** [comment]
仅当可拖动的元素和可以放置的元素可能是同一个的时候，selfTarget 才可能有正确的值，因为只有这样才能将目标放置在自身所在位置。

拖动过程中会在当前放置的元素上添加 `.drop-to` 类，但不会添加 `.drag-in` 类，拖放结束时会移除额外的类，如果没有移除可能是拖放结束时鼠标已经在浏览器窗口之外的，这种极端情况目前无法处理，但此时回到页面点击一下界面就会恢复正常。

因为仅仅是用法问题，此问题先关闭了。如果还有问题请再打开。
