### ISSUE TITLE
视图>树形菜单>树形导航菜单 文档已经过时了

### ISSUE THREAD

**Issue by blqw** [easysoft/zui#66]
http://zui.sexy/#view/tree

现在不是增加active类了 而是一个open-in  文档没更新

**Comment by catouse** [comment]
`active` 类的作用在树形菜单中是高亮当前选中的项目，与树形菜单的 `open` 和 `in` 的作用无关，主要区别如下：

* `active`：高亮当前选中的条目，这个条目可能是折叠状态，也可能是展开状态，可以在初始的时候指定，或者自己写 JavaScript 来动态更改，树形菜单上也可以不存在此类表示目前没有条目被选中；
* `open`：指示当前节点是展开状态，会显示此节点下的所有一级子节点，需要注意的是当一个节点没有任何子节点时，当前仍然会添加 `open` 类；
* `in`：当节点启用动画效果时会延时切换此类来实现过渡效果，一般使用时可以忽略。

因为你所描述的问题并不存在，所以此问题被关闭。

**Comment by blqw** [comment]
确实是我搞错了
