### ISSUE TITLE
下载的zui-1.7.0.dist.zip中没有找到tree目录

### ISSUE THREAD

**Issue by toypipi** [easysoft/zui#68]
请教，在使用树形菜单时，参考文档[树形菜单](http://zui.sexy/#view/tree/1)需要包含zui.tree.min.css和zui.tree.min.js这两个文件。但是我在下载的zui-1.7.0.dist.zip包中没有找到tree目录，也找不到这两个文件。
![tim 20170712170612](https://user-images.githubusercontent.com/13879860/28110790-03e1dfe2-6726-11e7-8344-4eeecffdb0c5.png)。谢谢！

**Comment by catouse** [comment]
这是文档上的一个错误，因为树形菜单已包含在标准版中。此错误已在开发版中修复。
