### ISSUE TITLE
chosen初始化问题

### ISSUE THREAD

**Issue by web-yuzm** [easysoft/zui#69]
chosen放在tabcontent非默认显示里面的都无法初始化；如果利用点击tab来做初始化也出现无法初始化只会变成普通的select；

**Comment by catouse** [comment]
理论上 chosen 与标签页没有冲突，如果你的chosen是通过ajax加载的，则需要加载完成后再进行初始化。
能提供示例代码创建一个 [gist](https://gist.github.com/) 或者 [jsfiddle](https://jsfiddle.net/) 吗？

**Comment by web-yuzm** [comment]
@catouse 

jsfiddle的地址：
https://jsfiddle.net/zd6guzdL/ 

问题请看：请看标签2
