### ISSUE TITLE
uploader方法上传到七牛云服务器，multipart_params把uptoken去掉了，导致图片上传到七牛失败

### ISSUE THREAD

**Issue by princessJoanna** [easysoft/zui#71]
解决方案 
zui.uploader.js 中
 BeforeUpload: function(uploader, file) {
                var multipartParamsOption = options.multipart_params;
                var params = {};
                if(options.sendFileName) params[options.sendFileName === true ? 'name' : options.sendFileName] = file.name;
                if(options.sendFileId) params[options.sendFileId === true ? 'uuid' : options.sendFileId] = file.id;
                params = $.extend(params, $.isFunction(multipartParamsOption) ? multipartParamsOption(file, params) : multipartParamsOption);
                // uploader.setOption('multipart_params', params);
                that.callEvent('onBeforeUpload', file);
            },
注释掉uploader.setOption('multipart_params', params);

使用
 $('table.table').each(function(){
          var _this=$(this);
          _this.uploader(
                  {
                      qiniu:{
                          uptoken_url:'/upload/genUpToken',
                          domain:'http://dkongjian.dkongjian.cn'
                      },
                      multipart_params:function () {
                          return {
                              token :_this.data('zui.uploader').qiniuEnable.token
                          };
                      },
                      lang:'zh_cn'
                  }
          );
      })

**Comment by catouse** [comment]
谢谢反馈，1.8中已修复。
