### ISSUE TITLE
听说是让我来这提bug？

### ISSUE THREAD

**Issue by mummyFly** [easysoft/zui#72]
自己看看自己是不是bug一堆。开发个东西起码的责任心有么？官方论坛自己看看有用么？干脆关了好不？qq群进去就有人推销广告？平时没人理吐槽一句受不了？玻璃心？笑尿

**Comment by mummyFly** [comment]
不愧是zui，倒数第一的ui框架。

**Comment by catouse** [comment]
可能 ZUI 真的坑了他一把。希望他没有丢掉工作～～～

**Comment by easysoft** [comment]
@mummyFly
论坛上绝大部分的是使用问题，而不是bug。浩哥也都在努力的回复。
我们也都有自己日常的开发功能。
就看到你像个傻缺一样在这儿叽叽歪歪，说什么责任心，没有看到你做过什么实质性的贡献。
qq群有人推销广告，都被我们踢了好不好。你去找一个比我们管理更严的群试试？傻缺。

**Comment by easysoft** [comment]
傻缺，再告诉你一件事情，开源软件我们是没有任何权利和义务去帮你做什么事情的。所以把你这幅嘴脸给我收起来。你没有任何资格来指责我们怎么样。

**Comment by mummyFly** [comment]
666

**Comment by lscho** [comment]
@mummyFly 

bug一堆在哪？没找出来就是造谣哦~

> 开发个东西起码的责任心有么。

回去初中课本翻翻什么是责任心，什么是没有责任心

> 官方论坛自己看看有用么？

你注册个github有用吗？干脆注销得了

> qq群进去就有人推销广告？

潜水两年没见过广告，难道是你发的广告？

> 平时没人理吐槽一句受不了？
> 
> 玻璃心？


![qq 20170728182559](https://user-images.githubusercontent.com/11583677/28713544-07201acc-73c2-11e7-8731-c92002304de4.png)

![qq 20170728182602](https://user-images.githubusercontent.com/11583677/28713560-0fb93fba-73c2-11e7-9721-5119203d8db8.png)

自己说的话自己过过脑子。。你要是真列出一堆bug是官方没有回复没有解决的，我敬你是条汉子。。如果没有，送你一句mmp
