### ISSUE TITLE
上传功能设置resize 方法的crop属性为true，没有实现剪切功能

### ISSUE THREAD

**Issue by princessJoanna** [easysoft/zui#73]

**Comment by catouse** [comment]
裁剪是在上传之前自动进行的，你得指定裁剪后的尺寸。完整选项实例：

```js
{
    width: 128,
    height: 128,
    crop: true,
    quuality: 90,
    preserve_headers: false
}
```

**Comment by princessJoanna** [comment]
我的上传是上传到七牛云服务器，加了裁剪功能后，上传就是失败，完整代码
 $('table.table').each(function(){
          var _this=$(this);
          _this.uploader(
                  {

                     filters:{
                    // 只允许上传图片或图标（.ico）
                     mime_types: [
                      {title: '图片', extensions: 'jpg,gif,png'},
                     ],
                     // 最大上传文件为 1MB
                     max_file_size: '1mb',


                   },
                      qiniu:{


                       uptoken_url:'/upload/genUpToken',
                          domain:'http://dkongjian.dkongjian.cn/'
                      },

                      multipart_params:function (file,paramss) {
                          return {
                              token :_this.data('zui.uploader').qiniuEnable.token
                          };

                      },
                     resize:{
                         width: 128,
                         height: 128,
                         crop: true,
                         quuality: 90,
                         preserve_headers: false

                        },



                     lang:'zh_cn',


                  }
          );
      })

**Comment by catouse** [comment]
提示了什么错误吗？

**Comment by princessJoanna** [comment]
控制台报错 zui.uploader.js:22 POST http://upload.qiniu.com/ 614 (status code 614)
﻿

​

**Comment by catouse** [comment]
https://segmentfault.com/q/1010000000398581

**Comment by catouse** [comment]
这个问题先关闭了，如果有问题你再打开。
