### ISSUE TITLE
数据表格的分页需要自己实现吗？

### ISSUE THREAD

**Issue by qzgyw** [easysoft/zui#75]
没有看到数据表格中有关分页的属性，使用数据表格只能自己实现分页吗？禅道的跟这个不一样么？实现的话用load？

**Comment by catouse** [comment]
ZUI 数据表格只负责显示数据，你可以配合 load 加载新的数据。

**Comment by qzgyw** [comment]
@catouse 禅道的分页组件在zui中有吗？

**Comment by catouse** [comment]
禅道是在服务器分页的，每次点击页码会刷新页面。

**Comment by qzgyw** [comment]
@catouse 哦   明白了   谢谢
