### ISSUE TITLE
IE11下数据表格中的日期字段排序无效

### ISSUE THREAD

**Issue by qzgyw** [easysoft/zui#76]
极速模式下正常，兼容模式及IE11下日期类型的排序无效，官方实例 http://zui.sexy/#view/datatable 也是这样

**Comment by catouse** [comment]
如果使用字符串来表示日期可能存在在部分浏览器总不兼容的问题，日期数据需要使用 new Date(2018, 1, 1, 12, 11, 00) 来存储，或者使用整数表示的时间戳。

因为仅仅是用法问题，这个问题先关闭了，如果还有问题请打开。
