### ISSUE TITLE
文件上传组件在IE下点击“选择文件”按钮无响应

### ISSUE THREAD

**Issue by wtslh** [easysoft/zui#78]
在IE11下，点击选择文件按钮没有作用，使用源码跟踪发现：
![image](https://user-images.githubusercontent.com/2245560/30008299-b2bd2b12-9150-11e7-996b-f18342a9c326.png)

在这行，永远都是执行return
希望能解决，谢谢。

**Comment by catouse** [comment]
经测试，选择文件按钮在IE11下工作正常。
你无需手动在 `.uplpader` 内添加 `<input type="file">` 按钮。
如果还有问题，可以贴出你的完整代码。
