### ISSUE TITLE
官方文档中Uploader部分可能存在笔误

### ISSUE THREAD

**Issue by wtslh** [easysoft/zui#80]
![image](https://user-images.githubusercontent.com/2245560/30111523-8dceecb8-9340-11e7-9b5b-c4cb7370d19e.png)
如图，“制定”应为“指定”
"fileFormater"应为"fileIconCreator"

**Comment by catouse** [comment]
已在开发版中更正，将随下个版本更新。

**Comment by vision4fun** [comment]
> prevent_duplicates：是否允许选取重复的文件，默认为 false 不允许，如果两个文件名和大小都相同则被认为是重复的文件

默认是 true

**Comment by catouse** [comment]
已更正。
