### ISSUE TITLE
datatable支持angular吗，在表格的a标签中的angular点击事件（click）失效

### ISSUE THREAD

**Issue by hardworkingman** [easysoft/zui#81]
![image](https://user-images.githubusercontent.com/21333949/30415322-28e01294-995a-11e7-8e00-a3c9cf03552a.png)

**Comment by catouse** [comment]
通常不建议在使用 angular 的情况下使用 zui 的 js 部分，这样可能让你的开发环境变得复杂。确保 dom 生成结束后才调用 datatable 的初始化操作，并且初始化之后，你再更新原来的 table 是无效的。
