### ISSUE TITLE
文件上传时需要点击两次才能上传。

### ISSUE THREAD

**Issue by ZbWeb** [easysoft/zui#84]
因为我的项目需要动态添加文件上传的按钮。所以我采用事件监听的方法去调用uploader()：

`
 $(document).on('click','.roomBtn',function () {
        $(this).uploader({
            autoUpload: true,// 当选择文件后立即自动进行上传操作
            lang: 'zh_cn',
            url: '/uploader/zui/upload',  // 文件上传提交地址
            filters: {
                mime_types:[{title: '图片文件', extensions: 'bmp,png,jpeg,jpg,gif'}]
            },
            multi_selection:false,
            file_data_name: 'file',
            limitFilesCount:1,
            chunk_size: 0,
            deleteActionOnDone: function (file, doRemoveFile) {
                return true;
            },
            responseHandler: function (responseObject, file) {

            }
        })
    })
`

但是在第一次使用文件上传时，必须点击两次上传按钮，才能打开选择文件的窗口。

**Comment by catouse** [comment]
uploader 仅需要初始化一次，不要将初始化部分的代码放在点击事件回调函数里面。如果你要在上传控件之外触发选择文件事件可以这样：

```js
// 获取 uploader 对象
var uploader = $('#myUploader').data('zui.uploader');

// 触发选择文件按钮点击事件
uploader.$button.trigger('click');
```

因为仅仅是使用方法的问题，先关闭了，如果有其他问题你再 open issue。
