### ISSUE TITLE
Win7+IE11下，页面加载后，控制台出现异常

### ISSUE THREAD

**Issue by wtslh** [easysoft/zui#87]
![image](https://user-images.githubusercontent.com/2245560/33871047-b469634c-df4b-11e7-9ae6-76d90c9d16f1.png)
版本： ZUI: Standard edition - v1.7.0 - 2017-06-17

**Comment by catouse** [comment]
请问是调用哪个组件出现上述问题？我测试是没有这个错误的。

**Comment by wtslh** [comment]
不确定是哪个组件导致该问题，当时对页面展示也没有影响，所以没继续跟踪。当时是在IE11，Chrome，360浏览器上都有这样的问题。
近期对页面做了很多调整，也没注意什么时候这个问题消失了。初步怀疑是脚本冲突导致的。
既然问题消失了，就关闭issue了。
谢谢。
