### ISSUE TITLE
真j8扯淡 ，表格说废弃就废弃，真脑残

### ISSUE THREAD

**Issue by phoenix-yassin** [easysoft/zui#96]

**Comment by catouse** [comment]
数据表格只是以后不会增加新功能了，在上周发布的 1.8.1 中仍然修复了关键 Bug，而且源码都在那里，自己想继续用还不简单。
新版数据表格2完全覆盖旧版功能，而且拥有更多功能，旧版本数据表格对于框架开发来说就没必要继续维护了。
对于大爷您，我只能说：走好，不送！

**Comment by easysoft** [comment]
SB一个。

**Comment by 523219809** [comment]
走好，不送

**Comment by salansun** [comment]
真j8扯淡 ，表格说废弃就废弃，真脑残

**Comment by sxdtzhaoxinguo** [comment]
走好,不送!

**Comment by ming-alone** [comment]
走好,不送!

**Comment by huang6349** [comment]
爱玩不玩

**Comment by wangyubest** [comment]
就你这SB，还搞什么IT，真给行业丢脸，别人免费提供，你特么还给老子长脸了，废物狗东西。

**Comment by qiankunshe** [comment]
你爱用不用，有本事自己去搞去，又没收你钱，还当大爷了

**Comment by kensmaster** [comment]
走好,不送!

**Comment by xinhui-hui** [comment]
这真是典型伸手党，长见识了

**Comment by wo4861069** [comment]
有毛病，你想要用老的组件，你可以用之前的版本，你想用新的肯定要升级版本，随便你，我觉得你不适合做程序员，或者开发，什么都是老一套，这样会被淘汰的，要多学习，新的东西，要会接收新的东西，这样才能有进步

**Comment by guanxiying** [comment]
无知并且无能的喷子，走好，不送！

**Comment by czwzgs** [comment]
走好，不送！

**Comment by ChaoshengZhang** [comment]
走好，不送

**Comment by ankyliu** [comment]
兄弟是有什么难处可以说出来，大家一起想办法。何必出言不逊？人家版本升级，你不想用可以继续用老版本。这么说话没道理。

**Comment by xihrni** [comment]
脑袋进水了？早点转行吧

**Comment by WEBTMM** [comment]
走好不送。。

**Comment by jacklee-2000** [comment]
社会在进步，寄生虫依旧存在，浪费习大爷中国制造、全民学习的精神。
中国不是缺乏创新，是缺乏创造。都这样靠别人寄生已经严重阻碍了中国IT行业的发展了

**Comment by fireware** [comment]
走好,不送!
